{
 "title": "Bankapp",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up{}", "legendFormat": "{{application}}" }
   ]
  },
  {
   "title": "Rates availability",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "exchange_rates_service_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_usage{application=\"front\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(login_total[5m])) by (is_success)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "95% percentile of server response duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, application) (rate(http_server_requests_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95% percentile of Kafka response duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, application) (rate(spring_kafka_template_seconds_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "400 errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"4..\"}[5m])) by (application)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "500 errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[5m])) by (application)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count[5m])) by (application)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Fails", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Failed transactions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum(rate(transfer_transaction_fails_total[5m])) by (direction)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks of transactions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum(rate(non_cash_blocks_total[5m]))",
     "legendFormat": "non cash"
    },
    {
     "expr": "sum(rate(cash_blocks_total[5m]))",
     "legendFormat": "cash"
    }
   ]
  },
  {
   "title": "Notification fails",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(rate(notification_delivery_fails_total[5]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}