server.port: ${SERVER_PORT}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

management:
  endpoints.web.exposure.include: info, health, metrics,prometheus
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}
  tracing:
    sampling:
      probability: ${ZIPKIN_TRACING_PROBABILITY}
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

application:
  CONFIRM_PROBABILITY: ${CONFIRM_PROBABILITY}