--DROP TABLE IF EXISTS transfers CASCADE;
--DROP TYPE transaction_status;

--CREATE TYPE transaction_status AS ENUM ('STARTED', 'TRANSFER', 'SUCCESS', 'ERROR');

DO
'
DECLARE
BEGIN
    CREATE TYPE transaction_status AS ENUM (''STARTED'', ''TRANSFER'', ''SUCCESS'', ''ERROR'');
EXCEPTION
    WHEN duplicate_object THEN null;
END;
' LANGUAGE PLPGSQL;


CREATE TABLE IF NOT EXISTS transfers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id UUID DEFAULT gen_random_uuid() UNIQUE,
  from_account UUID NOT NULL,
  to_account UUID NOT NULL,
  from_amount NUMERIC(14,2) NOT NULL CHECK(from_amount>=0),
  to_amount NUMERIC(14,2) NOT NULL CHECK(to_amount>=0),
  exchange_rate NUMERIC(14,2) NOT NULL CHECK(exchange_rate>=0),
  status TRANSACTION_STATUS NOT NULL,
  created_at timestamp DEFAULT NOW(),
  updated_at timestamp NOT NULL
);
