kafka:
  enabled: true
  fullnameOverride: "kafka"
  image:
    registry: docker.io
    repository: bitnamilegacy/kafka
  controller:
    enabled: true
    replicaCount: 3
    readinessProbe:
      initialDelaySeconds: 30
      periodSeconds: 30
      failureThreshold: 10
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 30
      failureThreshold: 10
  broker:
    replicaCount: 0
    persistence:
      size: 1Gi
    readinessProbe:
      initialDelaySeconds: 30
      periodSeconds: 30
      failureThreshold: 10
  clusterId: a1b2c3d4-e5f6-g7h8-i9j0-k1l2m3n4o5p6
  provisioning:
    enabled: true
    topics:
      - name: "bank-notifications"
        partitions: 2
        replicationFactor: 2
      - name: "bank-exchange-rates"
        partitions: 1
        replicationFactor: 2
  networkPolicy:
    enabled: false
  listeners:
    client:
      protocol: PLAINTEXT
    controller:
      protocol: PLAINTEXT
    interbroker:
      protocol: PLAINTEXT