server:
  fullnameOverride: prometheus-server
  ingress:
    enabled: true
    hosts:
      - prometheus.internal.com
  global:
    scrape_interval: 15s
serverFiles:
  alerting_rules.yml:
   groups:
     - name: "account service down"
       rules:
         - alert: InstanceDown
           expr: up{job="account"} == 0
           for: 1m
           labels:
             severity: critical
           annotations:
             summary: "Instance account service down"
     - name: "blocker service down"
       rules:
         - alert: InstanceDown
           expr: up{job="blocker"} == 0
           for: 1m
           labels:
             severity: critical
           annotations:
             summary: "Instance blocker service down"
     - name: "cash service down"
       rules:
         - alert: InstanceDown
           expr: up{job="cash"} == 0
           for: 1m
           labels:
             severity: critical
           annotations:
             summary: "Instance cash service down"
     - name: "exchange service down"
       rules:
         - alert: InstanceDown
           expr: up{job="exchange"} == 0
           for: 1m
           labels:
             severity: critical
           annotations:
             summary: "Instance exchange service down"
     - name: "exchange-generator service down"
       rules:
         - alert: InstanceDown
           expr: up{job="exchange-generator"} == 0
           for: 1m
           labels:
             severity: critical
           annotations:
             summary: "Instance exchange-generator service down"
     - name: "front service down"
       rules:
         - alert: InstanceDown
           expr: up{job="front"} == 0
           for: 1m
           labels:
             severity: critical
           annotations:
             summary: "Instance front service down"
     - name: "notifications service down"
       rules:
         - alert: InstanceDown
           expr: up{job="notifications"} == 0
           for: 1m
           labels:
             severity: critical
           annotations:
             summary: "Instance notifications service down"
     - name: "transfer service down"
       rules:
         - alert: InstanceDown
           expr: up{job="transfer"} == 0
           for: 1m
           labels:
             severity: critical
           annotations:
             summary: "Instance transfer service down"

     - name: CPU-alert
       rules:
         - alert: CPUAlert
           expr: system_cpu_usage>0.5
           for: 1m
           labels:
             severity: critical
           annotations:
             summary: "High CPU Usage"

  prometheus.yml:
    scrape_configs:
      - job_name: 'front'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: [ 'front:8080' ]
            labels:
              application: 'front'
      - job_name: 'account'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: [ 'account:8080' ]
            labels:
              application: 'accounts'
      - job_name: 'blocker'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: [ 'blocker:8080' ]
            labels:
              application: 'blocker'
      - job_name: 'cash'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: [ 'cash:8080' ]
            labels:
              application: 'cash'
      - job_name: 'exchange'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: [ 'exchange:8080' ]
            labels:
              application: 'exchange'
      - job_name: 'exchange-generator'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: [ 'exchange-generator:8080' ]
            labels:
              application: 'exchange-generator'
      - job_name: 'notifications'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: [ 'notifications:8080' ]
            labels:
              application: 'notifications'
      - job_name: 'transfer'
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: [ 'transfer:8080' ]
            labels:
              application: 'transfer'