--DROP TABLE IF EXISTS cash_transactions CASCADE;
--DROP TYPE currency;
--DROP TYPE transaction_status;
--DROP TYPE cash_action;

--CREATE TYPE currency AS ENUM ('RUB','USD','CNY');
--CREATE TYPE transaction_status AS ENUM ('STARTED', 'BLOCKING_REQUEST', 'BLOCKED', 'CASH_RECEIVED', 'DEPOSIT_PROCESSED',
-- 'CASH_WAS_GIVEN', 'SUCCESS', 'CANCEL', 'ERROR');
--CREATE TYPE cash_action AS ENUM ('DEPOSIT','WITHDRAWAL');

DO
'
DECLARE
BEGIN
    CREATE TYPE currency AS ENUM (''RUB'',''USD'',''CNY'');
EXCEPTION
    WHEN duplicate_object THEN null;
END;
' LANGUAGE PLPGSQL;

DO
'
DECLARE
BEGIN
    CREATE TYPE transaction_status AS ENUM (''STARTED'', ''BLOCKING_REQUEST'', ''BLOCKED'',
    ''CASH_RECEIVED'', ''DEPOSIT_PROCESSED'',''CASH_WAS_GIVEN'', ''SUCCESS'', ''CANCEL'', ''ERROR'');
EXCEPTION
    WHEN duplicate_object THEN null;
END;
' LANGUAGE PLPGSQL;

DO
'
DECLARE
BEGIN
    CREATE TYPE cash_action AS ENUM (''DEPOSIT'',''WITHDRAWAL'');
EXCEPTION
    WHEN duplicate_object THEN null;
END;
' LANGUAGE PLPGSQL;


CREATE TABLE IF NOT EXISTS cash_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id UUID DEFAULT gen_random_uuid() UNIQUE,
  action cash_action NOT NULL,
  user_id UUID NOT NULL,
  username VARCHAR(256) NOT NULL,
  account_id UUID NOT NULL,
  currency_string_code_iso4217 currency NOT NULL,
  amount NUMERIC(14,2) NOT NULL CHECK(amount>=0),
  status transaction_status NOT NULL,
  created_at timestamp DEFAULT NOW(),
  updated_at timestamp NOT NULL
  );
