replicaCount: 1

SPRING_APPLICATION_NAME: bankNotifications

KEYCLOAK_ISSUER_URI: http://keycloak:9080/realms/bankapp

DATASOURCE_URL: jdbc:postgresql://notifications-db:5432/data
DATASOURCE_USERNAME: user
DATASOURCE_PASSWORD: password

LOG_LEVEL: INFO

KAFKA_BOOTSTRAP_SERVERS: kafka:9092
KAFKA_NOTIFICATIONS_TOPIC: bank-notifications
KAFKA_SERVICE_LOG_TOPIC: notifications-log

ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans
ZIPKIN_TRACING_PROBABILITY: 1

MAIL_DELIVERY_ENABLED: false
SMTP_SERVER_HOST: smtp.mail.ru
SMTP_SERVER_PORT: "465"
MAIL_USERNAME: for_develop_test@mail.ru
MAIL_PASSWORD: password
FROM_MAIL_ADDRESS: for_develop_test@mail.ru
SENDER_NAME_FOR_MAIL: "Birbank LLC"

INITIAL_DELAY_SEC: 10

image:
  repository: mcat1980/bank-notifications
  tag: "20.0"
  pullPolicy: IfNotPresent

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: "notifications"

service:
  type: ClusterIP
  port: 8080

database:
  image:
    repository: postgres
    tag: "17.5"