admin:
  existingSecret: grafana-secret
ingress:
  enabled: true
  hosts:
    - grafana.internal.com
dashboards:
  default:
    spring-boot:
      file: dashboards/19004_rev1.json
    prometheus-stats:
      # Ref: https://grafana.com/dashboards/2
      gnetId: 2
      revision: 2
      datasource: Prometheus