apiVersion: v1
kind: Service
metadata:
  name: {{ include "front.fullname" . }}
  labels:
    {{- include "front.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 900
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "front.selectorLabels" . | nindent 4 }}
status: {}