apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "account.fullname" . }}
  labels:
    {{- include "account.labels" . | nindent 4 }}
data:
  SERVER_PORT: "8080"
  SPRING_APPLICATION_NAME: {{ .Values.SPRING_APPLICATION_NAME }}

  DATASOURCE_URL: jdbc:postgresql://{{ include "account.fullname" . }}-db:5432/data
  KEYCLOAK_ISSUER_URI: http://keycloak:9080/realms/bankapp

  LOG_LEVEL: {{ .Values.LOG_LEVEL }}

  SERVICE_URL_ACCOUNT: {{ .Values.SERVICE_URL_ACCOUNT }}

  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.KAFKA_BOOTSTRAP_SERVERS }}
  KAFKA_NOTIFICATIONS_TOPIC: {{ .Values.KAFKA_NOTIFICATIONS_TOPIC }}
  KAFKA_SERVICE_LOG_TOPIC: {{ .Values.KAFKA_SERVICE_LOG_TOPIC }}

  ZIPKIN_ENDPOINT: {{ .Values.ZIPKIN_ENDPOINT }}
  ZIPKIN_TRACING_PROBABILITY: {{ .Values.ZIPKIN_TRACING_PROBABILITY | quote}}

immutable: true
