apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "transfer.fullname" . }}
  labels:
    {{- include "transfer.labels" . | nindent 4 }}
data:
  SERVER_PORT: "8080"
  SPRING_APPLICATION_NAME: {{ .Values.SPRING_APPLICATION_NAME }}

  DATASOURCE_URL: jdbc:postgresql://{{ include "transfer.fullname" . }}-db:5432/data
  KEYCLOAK_ISSUER_URI: {{ .Values.KEYCLOAK_ISSUER_URI }}

  ZIPKIN_ENDPOINT: {{ .Values.ZIPKIN_ENDPOINT }}
  ZIPKIN_TRACING_PROBABILITY: {{ .Values.ZIPKIN_TRACING_PROBABILITY | quote}}

  LOG_LEVEL: {{ .Values.LOG_LEVEL }}

  SERVICE_URL_ACCOUNT: {{ .Values.SERVICE_URL_ACCOUNT }}
  SERVICE_URL_BLOCKER: {{ .Values.SERVICE_URL_BLOCKER }}
  SERVICE_URL_EXCHANGE: {{ .Values.SERVICE_URL_EXCHANGE }}
  SERVICE_URL_TRANSFER: {{ .Values.SERVICE_URL_TRANSFER }}

  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.KAFKA_BOOTSTRAP_SERVERS }}
  KAFKA_NOTIFICATIONS_TOPIC: {{ .Values.KAFKA_NOTIFICATIONS_TOPIC }}

immutable: true
