apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notifications.fullname" . }}
  labels:
    {{- include "notifications.labels" . | nindent 4 }}
data:
  SERVER_PORT: "8080"
  SPRING_APPLICATION_NAME: {{ .Values.SPRING_APPLICATION_NAME }}

  DATASOURCE_URL: jdbc:postgresql://{{ include "notifications.fullname" . }}-db:5432/data
  KEYCLOAK_ISSUER_URI: {{ .Values.KEYCLOAK_ISSUER_URI }}

  ZIPKIN_ENDPOINT: {{ .Values.ZIPKIN_ENDPOINT }}
  ZIPKIN_TRACING_PROBABILITY: {{ .Values.ZIPKIN_TRACING_PROBABILITY | quote }}

  LOG_LEVEL: {{ .Values.LOG_LEVEL }}

  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.KAFKA_BOOTSTRAP_SERVERS }}
  KAFKA_NOTIFICATIONS_TOPIC: {{ .Values.KAFKA_NOTIFICATIONS_TOPIC }}
  KAFKA_SERVICE_LOG_TOPIC: {{ .Values.KAFKA_SERVICE_LOG_TOPIC }}

  SMTP_SERVER_HOST: {{ .Values.SMTP_SERVER_HOST }}
  SMTP_SERVER_PORT: {{ .Values.SMTP_SERVER_PORT | quote }}
  MAIL_DELIVERY_ENABLED: {{ .Values.MAIL_DELIVERY_ENABLED | quote}}
  FROM_MAIL_ADDRESS: {{ .Values.FROM_MAIL_ADDRESS }}
  SENDER_NAME_FOR_MAIL: {{ .Values.SENDER_NAME_FOR_MAIL }}

immutable: true
