apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "notifications.fullname" . }}-db
spec:
  serviceName: {{ include "notifications.fullname" . }}-db
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "notifications.fullname" . }}-db
  template:
    metadata:
      labels:
        app: {{ include "notifications.fullname" . }}-db
    spec:
      containers:
          - name: {{ .Chart.Name }}-db
            image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
            imagePullPolicy: IfNotPresent
            env:
              - name: POSTGRES_DB
                value: data
              - name: POSTGRES_USER
                valueFrom:
                  secretKeyRef:
                    name: {{ include "notifications.fullname" . }}
                    key: DATASOURCE_USERNAME
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name:  {{ include "notifications.fullname" . }}
                    key: DATASOURCE_PASSWORD
            ports:
              - containerPort: 5432
            volumeMounts:
              - name: postgres-data
                mountPath: /var/lib/postgres/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "notifications.fullname" . }}-db
spec:
  clusterIP: None
  selector:
    app: {{ include "notifications.fullname" . }}-db
  ports:
      - name: 5432-5432
        port: 5432
        targetPort: 5432
        protocol: TCP