apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notifications.fullname" . }}
  labels:
    {{- include "notifications.labels" . | nindent 4 }}
stringData:
  DATASOURCE_USERNAME: {{ .Values.DATASOURCE_USERNAME }}
  DATASOURCE_PASSWORD: {{ .Values.DATASOURCE_PASSWORD }}
  MAIL_USERNAME: {{ .Values.MAIL_USERNAME }}
  MAIL_PASSWORD: {{ .Values.MAIL_PASSWORD }}
