--DROP TABLE IF EXISTS exchange_rates;
--DROP TYPE currency;

DO
'
DECLARE
BEGIN
    CREATE TYPE currency AS ENUM (''RUB'',''USD'',''CNY'');
EXCEPTION
    WHEN duplicate_object THEN null;
END;
' LANGUAGE PLPGSQL;

CREATE TABLE IF NOT EXISTS exchange_rates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  base CURRENCY NOT NULL,
  exchange CURRENCY NOT NULL,
  buy_rate NUMERIC(14,2) NOT NULL CHECK(buy_rate>=0),
  sell_rate NUMERIC(14,2) NOT NULL CHECK(sell_rate>=0),
  time timestamp,
  created_at timestamp DEFAULT NOW()
)
